using SDM.Application.Common.CQRS;

namespace SDM.Application.Products.UploadProductImage;

/// <summary>
/// Command that stores a new image for a product, replacing any existing one.
/// Carries the file data as a <see cref="Stream"/> so no file is buffered into
/// memory in the Application layer.
/// Handled by <see cref="UploadProductImageHandler"/>.
/// </summary>
public sealed class UploadProductImageCommand : ICommand<UploadProductImageResponse>
{
    /// <summary>Gets the unique identifier of the product to attach the image to.</summary>
    public Guid ProductId { get; init; }

    /// <summary>
    /// Gets the readable stream of the image data.
    /// The caller (controller) is responsible for disposing this stream after
    /// the command has been dispatched.
    /// </summary>
    public Stream FileStream { get; init; } = Stream.Null;

    /// <summary>
    /// Gets the original client-supplied file name.
    /// Used only to determine the file extension (e.g., <c>.jpg</c>, <c>.png</c>).
    /// A new unique name is generated by the storage service.
    /// </summary>
    public string FileName { get; init; } = string.Empty;

    /// <summary>
    /// Gets the MIME content type of the uploaded file (e.g., <c>image/jpeg</c>).
    /// Validated by <see cref="UploadProductImageValidator"/> before the handler runs.
    /// </summary>
    public string ContentType { get; init; } = string.Empty;

    /// <summary>
    /// Gets the byte length of the uploaded file.
    /// Validated by <see cref="UploadProductImageValidator"/> before the handler runs.
    /// </summary>
    public long FileSize { get; init; }
}
